export const CHANGE_LOGO_COLOR = 'CHANGE_LOGO_COLOR';
export const RESET_LOGO_COLOR = 'RESET_LOGO_COLOR';

export const CHANGE_BACK_COLOR = 'CHANGE_BACK_COLOR';
export const RESET_BACK_COLOR = 'RESET_BACK_COLOR';
